### ISSUE TITLE
[feature request] provide version number on download page

### ISSUE THREAD

**Issue by batkiz** [riok/Kreya#106]
Hi Kreya developers, I'd like to make Kreya could be installed with [scoop](https://scoop.sh/), but I couldn't find version number on download page, this makes it difficult to automate version upgrades and hashsum checks.

So could you provide version numbers on download page?

Best Regards,
batkiz.

**Comment by latonz** [comment]
Thank you for your request, we added this to our backlog. In the meantime you should be able to fetch the version from this endpoint: https://stable-downloads.kreya.app/appcast.json (should even be simpler to parse since it is json). We won't guarantee the format will keep the same forever, however we try our best to not introduce any breaking changes.
