### ISSUE TITLE
Support for paths in the endpoint

### ISSUE THREAD

**Issue by EAPR** [riok/Kreya#31]
Is possible to add support for paths, e.g. https://example.com/grpcweb/v1

**Comment by latonz** [comment]
We didn't have this use case on our radar since gRPC discourages hosting under a custom path. However, we think this should be supported by Kreya.

We're curious, could you provide us some more information about your use case? Do you use this successfully in production? What is your setup? Which technologies/languages/proxies do you use?

**Comment by EAPR** [comment]
I am using .net core/C# and hosting under IIS. Not in production yet, but it works well so far and the use of the custom paths allows me to organize more efficiently multiple endpoints. 

I was looking for a test tool and found Kreya and BloomRPC, and I like Kreya better, I find it more organized and efficient even though for this particular scenario BloomRPC already supports the custom paths.

**Comment by latonz** [comment]
Thank you for the additional information.

We plan to implement this in Kreya 1.4.

**Comment by EAPR** [comment]
Great!!

**Comment by latonz** [comment]
We just released Kreya 1.4.0-beta.2 which includes this feature: https://kreya.app/release-notes/beta. You can switch to the Beta release channel in the app via Kreya -> About. Change the release channel to Beta and search for updates. It should then install the newest Beta version. Please note that the Beta channel may contain some unstable features.

**Comment by EAPR** [comment]
I just tested it and works as expected.

**Comment by latonz** [comment]
BugFix is released with Kreya 1.4.
