### ISSUE TITLE
When I use envoy proxy, the response is Bad gRPC response Invalid content-type value: application/grpc-web+proto

### ISSUE THREAD

**Issue by flatcc** [riok/Kreya#35]
**Describe the bug**
There is a project, he uses envoyproxy, I am using Kreya's gRPC Web (Text) Mode, but the response is `Bad gRPC response Invalid content-type value: application/grpc-web+proto.`

**Comment by CommonGuy** [comment]
The `gRPC Web (Text)` mode expects the response to have a content type of `application/grpc-web-text`, meaning that the response payload has been base64 encoded.

Since you are receiving a response with the content type `application/grpc-web+proto`, you should be using the Kreya `gRPC Web` mode (without Text), which expects a binary response payload.

See https://github.com/grpc/grpc-web#wire-format-mode for more information between the two gRPC Web modes.

**Comment by flatcc** [comment]
Thank you! @CommonGuy

**Comment by CommonGuy** [comment]
Glad I could help :)
