### ISSUE TITLE
Cannot import 2 proto files with the same name in different directories

### ISSUE THREAD

**Issue by agoodsell5** [riok/Kreya#44]
**Describe the bug**
We have versioned proto files, so we have a folder named `v1` and a folder named `v2`. Inside these ideally we would have proto files with the same name, e.g. `customer_service.proto`. However, when we do this, Kreya is unable to import both services. If we name the _files_ something different they import perfectly. I think this feels like a bug to me.

**To Reproduce**
1. Create folder with service called `serviceA.proto`
2. Create  another folder with service called `serviceA.proto`
3. Try importing both of these at the same time using the folders parent folder has the import path
4. Only one service will be imported

**Expected behavior**
Both files should be imported, the name of the file should not determine if we can import it.

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - {
  "kreyaVersion": "1.5.0",
  "platform": "MacIntel",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}

**Comment by CommonGuy** [comment]
Yes, this is a bug in the current Kreya version. It will be fixed in the upcoming v1.6 release.

As an aside, the bug exists because we can only add proto files as relatives path (relative to the import path(s)). Given the following directory structure:
```
/root
  /v1
    serviceA.proto
  /v2
    serviceA.proto
```

The current Kreya version will first add `/root`, `/root/v1` and `/root/v2` as import paths, then the `serviceA.proto` file (only once, since duplicates are ignored). The upcoming Kreya version will only add `/root` as an import path and the files correctly as `v1/serviceA.proto` and `v2/serviceA.proto`.

Note that if you would add `/root/v1` and `/root/v2` manually as separate import paths, it will still not work in future versions, since the relative paths would still be the same. The import path has to be the parent `/root` folder.

**Comment by CommonGuy** [comment]
If you want, you can already try it out in the 1.6.0-beta.1 version by switching the release channel in the About window and checking for updates. Note that the beta version may contain bugs.

**Comment by CommonGuy** [comment]
V1.6 has been released
