### ISSUE TITLE
Non latin symbols don't display correctly

### ISSUE THREAD

**Issue by wasder** [riok/Kreya#62]
**Describe the bug**
Non latin symbols don't display correctly in responses.

**To Reproduce**
1. Make request to grpc which returns non latin symbols

![image](https://user-images.githubusercontent.com/2205216/141459995-e774d5ec-4fd3-4343-a607-8480d1a8761f.png)

**Expected behavior**
Displays other than latin symbols correctly, e.g. cyrillic

**Environment (if possible, copy the information from the error dialog or the About menu):**
```
 {
  "kreyaVersion": "1.7.0",
  "platform": "MacIntel",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}
```

**Comment by CommonGuy** [comment]
Thanks for bringing this up. This happens because the JSON serializer escapes these characters automatically. We'll fix this in the next release.

As a workaround, you can enter `$` in the "Response json path" field (lower right corner). This will display the symbols correctly, since it uses a different JSON engine.

**Comment by latonz** [comment]
V1.8 has been released and fixes this issue.
