### ISSUE TITLE
Better support for oneOf fields in the default request json/UI.

### ISSUE THREAD

**Issue by EraYaN** [riok/Kreya#74]
**Is your feature request related to a problem? Please describe.**
We use one_of a lot and Kreya just picks one (at random it seems) and displays that in the json in the request field.

**Describe the solution you'd like**
I'm not too sure, but some hint as to the existence of the other options in the UI might be good. Or to borrow ideas from BloomRPC put them in a nested <oneofname>_oneof block.

Maybe something like a darker/muted color if multiple are in the json for the unused ones. (with small radio buttons in front of them)?
Like how IDEs mute parts of `#ifdef` statements that are not in use for the current config.

**Describe alternatives you've considered**
Well I can always just type the name of the property if I remember it's name, but for discoverability it's not great.

**Comment by CommonGuy** [comment]
Due to the way the standard protobuf JSON serialization works, oneof fields are directly inlined into the parent message, without an extra "container". The generated JSON in the request field is just an example message, which only contains one of the oneof fields.

Did you know that you can press CTRL+Space to bring up all available fields (plus templating options)? By typing a quote, only the available fields will be listed:

https://user-images.githubusercontent.com/8035999/152166796-58bd6365-97e7-4a31-aa66-66939e08a1a5.mp4

**Comment by EraYaN** [comment]
This does not seem to generate the full json that I would expect of the sub object is just adds `{}` which is a shame.
And I guess we can always just type everything manually of course. But I'd like to just see all fields in one go, but maybe that is just not possible.

**Comment by baratgabor** [comment]
Actually, in our case I have no clue how could I send a specific value of `oneof`. What we're doing below is that we want to receive a list of filter definitions, all of which can be a string filter, number filter or date filter. The operators and the operands can differ, but they have the same field names. This is the pattern that was suggested to achieve a "repeated oneof" field.

```protobuf
message GridQuery
{
    ...
    repeated GridFilter filters = 2;
    
    message GridFilter {
        oneof filter {
            StringFilter stringFilter = 1;
            NumberFilter numberFilter = 2;
            DateFilter dateFilter = 3;
        }
    }

    message StringFilter
    {
        string column = 1;
        StringFilterOperator operator = 2;
        string operand = 3;

        enum StringFilterOperator
        {
            Invalid = 0;
            IsNotEmpty = 1;
            Equal = 2;
            NotEqual = 3;
            Contains = 4;
            StartsWith = 5;
            EndsWith = 6;
        }
    }

    message NumberFilter
    {
        string column = 1;
        NumberFilterOperator operator = 2;
        string operand = 3;

        enum NumberFilterOperator
        {
            Invalid = 0;
            Equal = 1;
            NotEqual = 2;
            LessThanOrEqual = 3;
            GreaterThanOrEqual = 4;
        }
    }

    message DateFilter
    {
        string column = 1;
        DateFilterOperator operator = 2;
        google.protobuf.Timestamp operand = 3;

        enum DateFilterOperator
        {
            Invalid = 0;
            IsNotNull = 1;
            Equal = 2;
            NotEqual = 3;
            LessThanOrEqual = 4;
            GreaterThanOrEqual = 5;
        }
    }
```

And the payload template in Kreya defaults to the following:

```json
  "filters": [
    {
      "column": "{{ faker.database.column }}",
      "operator": "Invalid",
      "operand": "fooBar"
    },
    {
      "column": "{{ faker.database.column }}",
      "operator": "Invalid",
      "operand": "fooBar"
    }
  ],
```

This template doesn't work even after correcting the values (and indeed, I see no way of the app being able to determine the correct type, since it's ambiguous):

`InvalidProtocolBufferException: Protocol message contained a tag with an invalid wire type.`

But if I'm doing something wrong I'd appreciate any suggestions. :) Maybe if I change the column, operator and operand field names to be unique for the given type that would help (even though it would feel artificial). I'm going to test it now.

**Comment by CommonGuy** [comment]
@baratgabor Which version of Kreya are you using? The generated example message should look like this
```
{
  "filters": [
    {
      "stringFilter": {
        "column": "{{ faker.database.column }}",
        "operator": "Invalid",
        "operand": "fooBar"
      }
    },
    {
      "stringFilter": {
        "column": "{{ faker.database.column }}",
        "operator": "Invalid",
        "operand": "fooBar"
      }
    }
  ]
}
```
The type is determined by the field name. You can right-click on the operation and select `Reset request(s)` to re-generate the example message.

**Comment by baratgabor** [comment]
@CommonGuy version is 1.7.0, but after I read your post I realized that I didn't hit "Run all importers" in Kreya to load the current protos. 🤦‍♂️

After refreshing, the generated example is indeed what you posted. So it was my mistake; sorry for taking your time.

(But btw, I'd think it's rather typical that people forget to load the new protos; maybe it would worth to consider adding some prominent notification that the models have changed.)

**Comment by CommonGuy** [comment]
@baratgabor No problem, glad that your issue is resolved. Regarding the notification, we added that to our backlog 👍

**Comment by CommonGuy** [comment]
Regarding the original request (listing all oneOf fields in the generated example message), we do not have any plans to implement this. In our opinion, the editor support of automatically suggesting all possible fields by pressing CTRL+Space should be enough for most use cases.

If you disagree and would like us to implement the requested functionality, please leave a comment or reaction. This will allow us to rethink our decision if there is enough demand for it.

**Comment by EraYaN** [comment]
I mean besides that it's just extra tedium, I think I've already given my 2 cents. ¯\\\_(ツ)\_/¯
