### ISSUE TITLE
Connecting without SSL authentication, but server has only secure connection

### ISSUE THREAD

**Issue by vekrei** [riok/Kreya#80]
**Description:**
My grpc server connects only via SSL/TLS authentication.
Server (based on example from https://grpc.io/docs/guides/auth/):
```
import grpc
import helloworld_pb2
from concurrent import futures

server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
with open('certificate.key', 'rb') as f:
    private_key = f.read()
with open('certificate.csr', 'rb') as f:
    certificate_chain = f.read()
server_credentials = grpc.ssl_server_credentials( ( (private_key, certificate_chain), ) )
server.add_secure_port('172.16.22.51:6066', server_credentials)
server.start()
```

Certificate generation:
```
openssl req -newkey rsa:2048 -nodes -keyout certificate.key -out certificate.csr -addext "subjectAltName = IP:172.16.22.51"
openssl x509 -signkey certificate.key -in certificate.csr -req -days 365 -out certificate.crt -extfile <(printf "subjectAltName=IP:172.16.22.51")
```

1. I want to connect to server via Kreya using this settings:
 <img width="542" alt="image" src="https://user-images.githubusercontent.com/101299510/157561398-7e5f96c7-be40-4189-bdbc-3ac6c6bf06d1.png">
And with these settings, my request is executed successfully on the server and a response is returned. But I have only secured connection on my server. What should I do so that requests are executed only when a certificate is presented?

2. When I change settings:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/101299510/157561983-c698d6e3-f009-41d4-95d1-f235e5894173.png">
<img width="991" alt="image" src="https://user-images.githubusercontent.com/101299510/157562070-bf28faf4-ab9e-4a74-bd15-02537e4ea423.png">
My server is still unavailable (Error 14)

When I change to pem certificates (generation like in https://dev.to/techschoolguru/how-to-create-sign-ssl-tls-certificates-2aai)
I also receive an error authentication exception, "The remote certificate is invalid according to the validation procedure (error 13)"

**Environment:**
 - OS: Mac OS Linux (M1)
 - Kreya Version 1.7.0

**Comment by CommonGuy** [comment]
If I understand the situation correctly, I think you are mixing things up a little.

If your server does NOT have a valid TLS certificate (which seems to be the case, since you generated the certificat yourself), you need to set the "Server certificate (TLS/SSL) validation" setting to _Disabled_. This allows Kreya to connect to your server, even though the server certificate is invalid.  
An alternative would be to add the certificate to the "trusted certificate list" of your OS, in which case Kreya would recognize the certificate as valid. In that case, you could leave the "Server certificate (TLS/SSL) validation" setting on _Enabled_.

To serve client TLS certificates when making Kreya calls, you did the right thing by configuring the certificate in Kreya. Did you also reference it in the _Auth_ tab? That should be enough to make TLS certificates work.
![grafik](https://user-images.githubusercontent.com/8035999/157893568-8d1459b9-c80a-4803-a294-1ef0b99a32c4.png)

Now, if you have an invalid server certificate and want to send a TLS client certificate, you need to set "Server certificate (TLS/SSL) validation" to _Disabled_, but still reference the client certificate in the _Auth_ tab. Does that work for you?

**Comment by vekrei** [comment]
It turns out that with the help of Kreya I can connect to my SECURE (server.add_secure_port('172.16.22.51:6066', server_credentials)) server without the corresponding certificate. I understand correctly?

It must also violate the security policy. I want my system to be completely secure: i.e. so that without a correct certificate I could not connect to the server. What should I do so that, regardless of the situation, I could not connect to my secure server without a correct certificate?

Yes, I referred to the above certificate in Auth:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/101299510/158247192-7ba01b14-5bbc-4b6a-b4b5-cc5a0a21f9c9.png">
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/101299510/158247232-7e2b5d55-9f52-4396-91b4-52db2839f166.png">

**Comment by CommonGuy** [comment]
If you are able to connect to your server with the settings from the screenshot, things are already looking good. It means that your server certificate is valid.

To test whether your server is "completely secure" and can only be accessed when providing a valid client certificate, remove the `cert` in the Auth settings temporarily. Then call your server. If you get an error, everything is fine, your server correctly expects a client certificate and rejects connections without one.

**Comment by vekrei** [comment]
_To test whether your server is "completely secure" and can only be accessed when providing a valid client certificate, remove the cert in the Auth settings temporarily_ - In this case, the parameter 'Server certificate (TLS/SSL) validation' must be enabled or not?

Can you please explain how the "Server certificate (TLS/SSL) validation" function works? Because I have not seen this in other grpc clients: 
Оnly a secure connection is available on our server
`server.add_secure_port('172.16.22.51:6066', server_credentials)`
But at the same time, when the "Server certificate (TLS / SSL) validation" parameter disabled, we can still correctly send requests to the server and receive a response from it.
