### ISSUE TITLE
Screen blinking

### ISSUE THREAD

**Issue by ppcamp** [riok/Kreya#85]
**Describe the bug**
For some reason, the screen unexpectedly started blinking.

**To Reproduce**
1. Make some gRPC web/text request
2. Open another program (maximized)
3. Go back to Kreya

**Expected behavior**
It shouldn't blinking the elements. I think that maybe this error is due to electron,  'cause it only happened once.

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 11
 - Kreya: 1.7.0
 - platform: Win32

**Comment by CommonGuy** [comment]
Yes, the logfile of Kreya is stored at `%APPDATA%/Kreya/kreya.log`. It would be nice if you could attach it to the issue.

**Comment by ppcamp** [comment]
> Yes, the logfile of Kreya is stored at `%APPDATA%/Kreya/kreya.log`. It would be nice if you could attach it to the issue.

I've checked and this file doesn't exist. There's only a `kreya.db` file, which I **guess** that's a sqlite file to the gRPC requests/responses.

I've also tried (unsuccessfully) to find the kreya folder in the following paths:
- `AppData/LocalLow`
- `AppData/Local`
- `C:/ProgramData`

**Comment by CommonGuy** [comment]
If it doesn't exist, then Kreya did not log anything yet (which is fine, we only log errors). As the blinking screen was probably not caused by an exception, it did not log any error to the log file.

Until the blinking screen happens again and we are able to reproduce this issue, it will be difficult to fix this bug...
