### ISSUE TITLE
support rich error responses

### ISSUE THREAD

**Issue by latonz** [riok/Kreya#9]
**Is your feature request related to a problem? Please describe.**
Currently rich error content's can't be viewed via Kreya.

**Describe the solution you'd like**
I would like to see the details of the error status ([Status.proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto)).

**Comment by CommonGuy** [comment]
This is supported in V1.2.0 of Kreya.

**Comment by kristijanhusak** [comment]
@CommonGuy How can I see the parsed details? Currently I'm seeing this:
```json
{
  "code": 3,
  "message": "Validation error",
  "details": [
    {
      /* Could not find any type in the set of imported protos */
      "@type": "type.googleapis.com/google.rpc.BadRequest",
      "value": "CigKCFVzZXJuYW1lEhxVc2VybmFtZSBpcyBhIHJlcXVpcmVkIGZpZWxk"
    }
  ]
}
```

**Comment by CommonGuy** [comment]
@kristijanhusak Because the `google.rpc.BadRequest` type isn't imported, Kreya cannot parse the error details. Protobuf messages cannot be deserialized without knowing their type definition.

A simple solution would be to download https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto (that is where the `google.rpc.BadRequest` type is defined) and add it to your Kreya importer.

Or, if you are already using types from the googleapis definitions and have them downloaded on your system, you could add an import to one of your protobuf files:
```protobuf
import "google/rpc/error_details.proto";
```

**Comment by danielalexis** [comment]
> add it to your Kreya importer.

Just FYI for future people reading this, it should be the same import as your current proto files, if its a new importer it won't read anything (guessing this happens due to no operations being generated from any file on that specific importer) and you will have the same problem.
